apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookapp
spec:
  replicas: 1
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          image: bookapp-frontend:1.0
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 80 }]
          volumeMounts:
            - name: frontend-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
      volumes:
        - name: frontend-config
          configMap:
            name: app-config
            items:
              - key: config.js
                path: config.js

